//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LG_Dashboard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Preset()
        {
            this.PresetFurnishingStyles = new HashSet<PresetFurnishingStyle>();
            this.Appliances = new HashSet<Appliance>();
        }
    
        public int PresetId { get; set; }
        public int AreaId { get; set; }
        public string Name_EN { get; set; }
        public string Name_FR { get; set; }
        public string ImageUrl { get; set; }
        public string ThumbUrl { get; set; }
        public string InternalName { get; set; }
        public string DefaultColour { get; set; }
    
        public virtual Area Area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PresetFurnishingStyle> PresetFurnishingStyles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appliance> Appliances { get; set; }
    }
}
