//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LG_Dashboard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PresetFurnishingStyle
    {
        public int PresetFurnishingStyleId { get; set; }
        public int StyleId { get; set; }
        public int FurnishingId { get; set; }
        public int PresetId { get; set; }
        public bool IsDefault { get; set; }
    
        public virtual Furnishing Furnishing { get; set; }
        public virtual Preset Preset { get; set; }
        public virtual Style Style { get; set; }
    }
}
