//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LG_Dashboard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductHotspotFeature
    {
        public int ProductId { get; set; }
        public int HotspotId { get; set; }
        public int FeatureId { get; set; }
    
        public virtual Feature Feature { get; set; }
        public virtual Hotspot Hotspot { get; set; }
        public virtual Product Product { get; set; }
    }
}
