//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LG_Dashboard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSpecification
    {
        public int ProductSpecificationId { get; set; }
        public int ProductId { get; set; }
        public int SpecificationId { get; set; }
        public string SpecValue_EN { get; set; }
        public Nullable<int> SpecificationImageId { get; set; }
        public string SpecValue_FR { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual SpecificationType SpecificationType { get; set; }
        public virtual SpecificationImage SpecificationImage { get; set; }
    }
}
