//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LG_Dashboard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Images = new HashSet<Image>();
            this.ProductHotspotFeatures = new HashSet<ProductHotspotFeature>();
            this.ProductSpecifications = new HashSet<ProductSpecification>();
            this.Categories = new HashSet<Category>();
            this.Certifications = new HashSet<Certification>();
        }
    
        public int ProductId { get; set; }
        public int AreaId { get; set; }
        public int ColorId { get; set; }
        public string Name_EN { get; set; }
        public string Name_FR { get; set; }
        public string Description_EN { get; set; }
        public string Description_FR { get; set; }
        public decimal MSRP { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public string ModelNumber { get; set; }
        public string BestBuyWebCode { get; set; }
        public string Disclaimer_EN { get; set; }
        public string Disclaimer_FR { get; set; }
        public string ThumbnailUrl { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateLastEdited { get; set; }
        public bool IsAutoArchive { get; set; }
        public bool IsManualArchive { get; set; }
        public bool IsCatalogOnly { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Color Color { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductHotspotFeature> ProductHotspotFeatures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSpecification> ProductSpecifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Certification> Certifications { get; set; }
    }
}
