//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LG_Dashboard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Session()
        {
            this.TrackingProducts = new HashSet<TrackingProduct>();
            this.TrackingFeatures = new HashSet<TrackingFeature>();
            this.TrackingSearches = new HashSet<TrackingSearch>();
        }
    
        public int SessionId { get; set; }
        public int RetailerId { get; set; }
        public string Hash { get; set; }
        public string Email { get; set; }
        public System.DateTime StartTimestamp { get; set; }
        public Nullable<System.DateTime> EndTimestamp { get; set; }
    
        public virtual Retailer Retailer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrackingProduct> TrackingProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrackingFeature> TrackingFeatures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrackingSearch> TrackingSearches { get; set; }
    }
}
