//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LG_Dashboard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecificationType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SpecificationType()
        {
            this.ProductSpecifications = new HashSet<ProductSpecification>();
        }
    
        public int SpecificationId { get; set; }
        public string SpecType_EN { get; set; }
        public string Units_EN { get; set; }
        public bool IsFilterable { get; set; }
        public string SortName { get; set; }
        public string SpecType_FR { get; set; }
        public string Units_FR { get; set; }
        public string InternalName { get; set; }
        public bool IsVisible { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSpecification> ProductSpecifications { get; set; }
    }
}
