//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LG_Dashboard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackingSystemLog
    {
        public int SystemLogId { get; set; }
        public string Exception { get; set; }
        public string StackTrace { get; set; }
        public System.DateTime Timestamp { get; set; }
    }
}
